
def hyperuniform_tiling(
    catalogfile,
    outputdir,
    ):
    """
    This main program read in a galaxy catalog, and arrange tiles according to the galaxy number density.
    
    Parameters
    ----------
    catalogfile : str : input fits file for galaxy catalog
    outputdir : str : output directory
    
    Main steps and outputs
    ----------
    1. read galaxy catalogue (ra,dec)
      > input galaxy catalog file
    2. make mask if not provided
      > output mask file
      > output galaxy counts map
    3. define cluster region
      > output cluster region map
    4. set tile mass map, which is proportional to 1 / galaxy counts per pixel
      > output tile mass map
    5. downsample galaxy as tiles, and set tile mass according to the tile mass map
      > output tile initial distribution (ra, dec)
      > output tile mass, color-coding (normalized tile mass array)
    6. evolve with anti-gravity alogirhtm
      > output tile distribution in iterations
    7. end
      > output tile final distribution
    
    """

    import numpy as np
    from astropy.io import fits
    import healpy as hp
    from  just_tiling.hyperuniform.hyperuniform_utils import change_mask_nside, move_on_sphere
    
    #catalogfile = './testdata/lightcone_ra_0_90_dec_0_90_rmagcut20.5_cluster_mask.fits'
    #outputdir = './testdata/'

    print(f"BEGIN HYPERUNIFORM TILING")
    
    write_cluster_region_map = True
    write_gal_counts_map = True
    write_tile_mass_map = True
    write_tile_initial = True
    write_tile_steps = False
    write_tile_final = True
    
    ### read galaxy catalogue
    
    print(f"reading catalog file {catalogfile} ...")
    hdul = fits.open(catalogfile)
    header = hdul[1].header
    data = hdul[1].data
    
    ra = data['ra']
    #print(ra)
    dec = data['dec']
    cluster = data['cluster_mask']
    
    ngaltot = len(ra)
    
    print(f"number of galaxies: {ngaltot}")
    print(f"number of cluster nearby galaxies: {sum(cluster)}")
    print("=="*20)
    
    
    ### set mask
    # so far the mask is generated by the galaxy catalogue using a low nside
    # finally the mask should be provided with the galaxy catalog
    
    print(f"setting mask ...")
    nside = 256
    npix = hp.nside2npix(nside)
    print(f"pixel number: {npix}")
    
    resolution = hp.pixelfunc.nside2resol(nside, arcmin=True)
    print(f"resolution: {resolution:.2f} arcmin")
    
    theta = np.deg2rad(90-dec)
    phi = np.deg2rad(ra)
    
    pix_indices = hp.ang2pix(nside, theta, phi, nest=False)
    counts_map = np.bincount(pix_indices, minlength=npix)
    mask = counts_map == 0
    visible = ~mask
    
    numbermask = mask.sum()
    numbervisible = visible.sum()
    print(f"number of mask pixel: {numbermask:d}")
    print(f"number of visible pixel: {numbervisible:d}")
    
    np.savez_compressed(outputdir+'mask_from_gal.npz', mask)
    
    if write_gal_counts_map:
        counts_map_plot = counts_map.astype(np.float32)
        counts_map_plot[mask] = hp.UNSEEN
    
        print(f"writing galaxy counts map file")
        np.savez_compressed(outputdir+'gal_counts_map.npz', counts_map_plot)
    
    print("=="*20)
    
    ### set cluster region
    
    print(f"set cluster region ...")
    
    flag1 = cluster==1
    flag2 = cluster==0
    
    cluster_ra = ra[flag1]
    cluster_dec = dec[flag1]
    
    nside_cl = 256
    npix_cl = hp.nside2npix(nside_cl)
    
    cluster_theta=np.deg2rad(90-cluster_dec)
    cluster_phi=np.deg2rad(cluster_ra)
    
    pix_indices_cluster = hp.ang2pix(nside_cl, cluster_theta, cluster_phi, nest=False)
    
    pix_indices_inside = hp.ang2pix(nside_cl, theta, phi, nest=False)
    
    cluster_map = np.zeros(npix_cl, dtype=np.float32)
    
    cluster_map[:] = hp.UNSEEN   # set unseen region
    cluster_map[pix_indices_inside] = 0   # set survey region
    cluster_map[pix_indices_cluster] = 2   # set cluster region
    
    if write_cluster_region_map:
        print(f"writing cluster_region_map file")
        np.savez_compressed(outputdir+f"cluster_region_map.npz", cluster_map)
    
    print("=="*20)
    
    
    ### set mass map for tile
    
    print(f"getting galaxy number density map and convert to tile mass map...")
    
    galdensity = ngaltot/numbervisible
    print(f"galaxy number density per pixel: {galdensity:.6f}")
    
    massmap = np.zeros(npix)
    massmap[visible] = galdensity/counts_map[visible] # high number counts => low tile mass
    massmap[mask] = hp.pixelfunc.UNSEEN
    
    if write_tile_mass_map:
        print(f"writing tile mass map file")
        np.savez_compressed(outputdir+f"gal_tile_mass_map.npz", massmap)
    
    print(f"=="*20)
    
    
    ### downsample the galaxy catalog to make initial tile distribution
    
    print(f"making initial tile distrubtion ...")
    
    numtile=12000  # target number of tiles
    
    # define regions for tiles
    # in principle this could be different from the mask for galaxy catalog
    
    dec0 = 0
    dec1 = 90
    ra0 = 0
    ra1 = 90
    
    trim_mask = (
          ( ra > ra0 )
        & ( ra < ra1 )        
        & ( dec > dec0 )
        & ( dec < dec1 )
        )
    
    ngal_for_tile = np.sum(trim_mask)
    print(f"galaxy catalog is trimmed from {ngaltot:d} to {ngal_for_tile:d} to avoid boundary")
    
    dec_mask = dec[trim_mask]
    ra_mask = ra[trim_mask]
    
    fraction = numtile/ngal_for_tile
    print(f"downsample fraction = {fraction:.6g}")
    
    tmpindex = np.linspace(0,int(ngal_for_tile-1),int(ngal_for_tile),dtype=int)
    
    # select luck galaxies according to the tile/galaxy ratio
    rng = np.random.default_rng(seed=42)
    lucky = rng.choice(tmpindex,size=numtile,replace=False)
    
    theta2 = np.deg2rad(90-dec_mask[lucky])
    phi2 = np.deg2rad(ra_mask[lucky])
    
    # get the healpix pixel id for each tile
    pix_indices2 = hp.ang2pix(nside, theta2, phi2, nest=False)
    
    # set the mass of tile as the mass in mass map
    mass2 = massmap[pix_indices2]
    
    massmin = mass2.min()
    massmax = mass2.max()
    print(f"min,max,mass: {massmin:.4f},{massmax:.4f}")
    print(f"average tile mass: {np.sum(mass2)/len(mass2):.6f}")
    
    if write_tile_initial:
        print(f"writing initial tile distribution files")
        tile_coord = np.column_stack((ra_mask[lucky], dec_mask[lucky]))
        np.savez_compressed(outputdir+f"hyper_initial_tile.npz",tile_coord=tile_coord)  # shape (n_tiles, 2): RA, Dec [deg]
    
    # set the color for plotting
    colors=(mass2-massmin)/(massmax-massmin)
    
    if write_tile_initial or write_tile_final or write_tile_steps :
        print(f"writing tile color coding file")
        np.savez_compressed(outputdir+f"hyper_tile_colors.npz", color=colors)
        np.savez_compressed(outputdir+f"hyper_tile_mass.npz", mass=mass2)
    
    print("=="*20)
    
    
    ### set density map with new resolution
    
    print(f"evolving the tiles according anti-gravity")
    
    # new nside, not neccesary same as the nisde for mass map
    nsidepm=1024
    npixpm = hp.nside2npix(nsidepm)
    resolutionpm = hp.pixelfunc.nside2resol(nsidepm, arcmin=True)
    
    maskpm, visiblepm = change_mask_nside(
        mask,
        nside_out = nsidepm,
        threshold = 0.0,
    )
    
    print(f"nsidepm={nsidepm:d}",f", number of pixels={npixpm:d}")
    print(f"resolution: {resolutionpm:.2f} arcmin")
    print(f"number of visible={visiblepm.sum():d}",f", number of mask={maskpm.sum():d}")
    
    areamask = maskpm.sum()
    areavisible = visiblepm.sum()
    #print(f"check pixel number consistency:",areamask,areavisible,areamask+areavisible)
    
    mass2tot = mass2.sum()
    print(f"total mass from tile catalog = {mass2tot:.6f}")
    avgden = mass2tot/areavisible
    
    pix_indicespm = hp.ang2pix(nsidepm, theta2, phi2, nest=False)
    mass_mappm = np.bincount(pix_indicespm, minlength=npixpm,weights=mass2)
    
    print(f"total mass from tile map = {mass_mappm.sum():.6f}")
    
    mass_mappm = mass_mappm/avgden
    #mass_mappm[unseenmaskpm]=hp.pixelfunc.UNSEEN
    mass_mappm[maskpm] = 1.
    
    
    ### anti-gravity algorithm 
    
    lmax = nsidepm*2
    movefactor = 1
    niter = 30
    
    thetatmp = theta2.copy()
    phitmp = phi2.copy()
    
    pixel_size = hp.nside2resol(nsidepm)
    
    for istep in range(niter):
    
        print(f"iteration {istep+1:02d}")
        # cic mass assignment
        pixels, weights = hp.get_interp_weights(
            nsidepm,
            thetatmp,
            phitmp,
            nest=False,
        )
    
        # avoid mass assignment for outside region
        weights_masked = np.where(
            visiblepm[pixels],
            weights,
            0.0,
        )
    
        # renormalize the tile weighting 
        weight_sum = weights_masked.sum(axis=0)
        good_particles = weight_sum > 0
        
        weights_masked[:, good_particles] /= (
            weight_sum[good_particles][None, :]
        )
    
        # tile mass map
        mass_mappm = np.bincount(
            pixels.ravel(),
            weights=(weights_masked * mass2[None, :]).ravel(),
            minlength=npixpm,
        )
    
        print(f"mass conservation check: {mass2.sum():.6f}, {mass_mappm.sum():.6f}")
    
        avgden = mass_mappm[visiblepm].sum() / visiblepm.sum()
    
        delta = np.zeros(npixpm, dtype=np.float64)
    
        delta[visiblepm] = (
            mass_mappm[visiblepm] / avgden - 1.0
        )
    
        print(f"average density in visible region: {delta[visiblepm].mean():.6g}")
        
        # set masked region as zero density
        delta[maskpm] = 0.0
    
        # harnomics
        delta_alm = hp.map2alm(
            delta,
            lmax=lmax,
            iter=3,
        )
    
        # Gaussian beam
        beam = hp.gauss_beam(
            fwhm=1.5 * pixel_size,
            lmax=lmax,
        )
    
        delta_alm = hp.almxfl(delta_alm, beam)
    
        cl = hp.alm2cl(delta_alm)
        ell_cl = np.arange(len(cl))
        variance = np.sum(
            (2 * ell_cl + 1) * cl
        ) / (4 * np.pi)
    
        rms_before = np.sqrt(variance)
        
        ell, emm = hp.Alm.getlm(lmax)
    
        phi_alm = np.zeros_like(delta_alm)
        nonzero_ell = ell > 0
        phi_alm[nonzero_ell] = (
            -delta_alm[nonzero_ell]
            / (ell[nonzero_ell] * (ell[nonzero_ell] + 1))
        )
        
        # gradient on sphere
        _, d_theta_map, d_phi_map = hp.alm2map_der1(
            phi_alm,
            nside=nsidepm,
            lmax=lmax,
        )
    
        dtheta = hp.get_interp_val(
            d_theta_map, thetatmp, phitmp
        )
        dphi = hp.get_interp_val(
            d_phi_map, thetatmp, phitmp
        )
    
        # setting maximum movement as 0.2 pixel size
        grad_norm = np.hypot(dtheta, dphi)
        max_grad = grad_norm.max()
    
        if max_grad == 0:
            break
    
        step = movefactor * pixel_size / max_grad
    
        # calculate new particle position and determine whether they can be moved
        # if the new position is outside the region, reject
        theta_candidate, phi_candidate = move_on_sphere(
            thetatmp,
            phitmp,
            dtheta,
            dphi,
            step,
        )
    
        candidate_pixels = hp.ang2pix(
            nsidepm,
            theta_candidate,
            phi_candidate,
            nest=False,
        )
        
        can_move = visiblepm[candidate_pixels]
        
        # update particle positions
        thetatmp[can_move] = theta_candidate[can_move]
        phitmp[can_move] = phi_candidate[can_move]
    
        print(
            "accepted:",
            can_move.sum(),
            "rejected:",
            (~can_move).sum(),
        )
     
        print(f"theta,min,max: {thetatmp.min()/np.pi*180:.2f} , {thetatmp.max()/np.pi*180:.2f}")
        print(f"phi,min,max: {phitmp.min()/np.pi*180:.2f} , {phitmp.max()/np.pi*180:.2f}")
    
        print(
            f"rms(delta)={rms_before:.6f}",
            f", step={step:.6g}",
            f", max_move={step * max_grad:.6g}",
        )
    
        if write_tile_steps:
            ratmp = np.rad2deg(phitmp)
            dectmp = 90-np.rad2deg(thetatmp)
    
            print(f"writing tile distribution files for iteration {istep+1:02d}")
            tile_coord = np.column_stack((ratmp, dectmp))
            np.savez_compressed(outputdir+f"hyper_step{istep+1:02d}_tile.npz",tile_coord=tile_coord)  # shape (n_tiles, 2): RA, Dec [deg]
    
        print("--"*20)
    
    if write_tile_final:
        ratmp=np.rad2deg(phitmp)
        dectmp=90-np.rad2deg(thetatmp)
        print(f"writing tile final distribution files")
        tile_coord = np.column_stack((ratmp, dectmp))
        np.savez_compressed(outputdir+f"hyper_final_tile.npz",tile_coord=tile_coord)  # shape (n_tiles, 2): RA, Dec [deg]
    
